version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:14

jobs:
  build-and-deploy:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Tests
          command: npm test
      - run:
          name: Build Application
          command: npm run build
      - add_ssh_keys:
          fingerprints:
            - "<<fingerprint_of_your_ssh_key>>"
      - run:
          name: Deploy to EC2
          command: |
            ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_IP << 'EOF'
              cd /var/www/node-app || mkdir -p /var/www/node-app && cd /var/www/node-app
              sudo rm -rf *
              exit
            EOF
            scp -o StrictHostKeyChecking=no -r ./* $EC2_USER@$EC2_IP:/var/www/node-app
            ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_IP << 'EOF'
              cd /var/www/node-app
              npm install --production
              pm2 stop all || true
              pm2 start server.js
              exit
            EOF

workflows:
  version: 2
  build-and-deploy-workflow:
    jobs:
      - build-and-deploy
