version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Test Application
          command: npm test

  deploy:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install SSH Key
          command: |
            mkdir -p ~/.ssh
            echo "$EC2_SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
      - run:
          name: Deploy to EC2
          command: |
            ssh -o StrictHostKeyChecking=no ubuntu@ec2-18-140-51-185.ap-southeast-1.compute.amazonaws.com << EOF
              cd /var/www/my-node-app
              git pull origin main
              npm install
              pm2 restart all || pm2 start index.js --name my-node-app
            EOF

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
